### ISSUE TITLE
[Bug Report] Link not working in Docs

### ISSUE THREAD

**Issue by PerFrivik** [isaac-sim/IsaacLab#544] opened 2024-06-20 08:15 UTC
### Describe the bug

The extension template [link](https://github.com/isaac-sim/IsaacLab.ext_template) on the following page: https://isaac-sim.github.io/IsaacLab/source/setup/template.html sends me to a github page not found.

**Comment by AugustDG** [comment] 2024-06-21 13:38
Duplicate of #457

**Comment by Mayankm96** [comment] 2024-06-23 06:32
Closing this issue since it is a duplicate.

**Closed by Mayankm96** 2024-06-23 06:32 UTC
Labels: duplicate
