### ISSUE TITLE
IsaacLab.ext_template

### ISSUE THREAD

**Issue by fighting-j** [isaac-sim/IsaacLab#558] opened 2024-06-24 13:24 UTC
When I build my own project according to the Isaaclab documentation, I open the extension module but get an error that the page cannot be found.
I get the following error when using git clone：
fatal: 'https://github.com/isaac-sim/IsaacLab.ext_template/' Authentication failed
When will the expansion module be released?

**Comment by KyleM73** [comment] 2024-06-24 14:41
the extension is here:

https://github.com/isaac-orbit/orbit.ext_template

it requires a little work to make it compatible with current isaac lab, changing the names of the packages in the toml/setup files, etc. it will likely be updated but hasn't yet.

**Comment by jsmith-bdai** [comment] 2024-06-24 17:05
The Isaac Lab team is actively working on updating this Extension Template, so it will be available very soon! Sorry for any convenience in the meantime

Closing as this is a duplicate of https://github.com/isaac-sim/IsaacLab/issues/457

**Closed by jsmith-bdai** 2024-06-24 17:05 UTC
