### ISSUE TITLE
[Question] Installing Isaac Lab using pip. FileNotFoundError.

### ISSUE THREAD

**Issue by timswim** [isaac-sim/IsaacLab#627] opened 2024-07-03 14:21 UTC
### Question
Hello! I have a question about installing Isaac Lab. I had no problems installing it a week ago on Desktop Ubuntu 22.04 LTS PC, but now when I try to install Isaac Lab using pip on Ubuntu Server 22.04 LTS, I get this error

> ./isaaclab.sh --install
`.....`
`File "/home/user/Python_projects/IsaacLab/.vscode/tools/setup_vscode.py", line 163, in <module>
    main()
  File "/home/user/Python_projects/IsaacLab/.vscode/tools/setup_vscode.py", line 126, in main
    isaaclab_settings = overwrite_python_analysis_extra_paths(isaaclab_template_settings)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Python_projects/IsaacLab/.vscode/tools/setup_vscode.py", line 49, in overwrite_python_analysis_extra_paths
    raise FileNotFoundError(f"Could not find the isaac-sim settings file: {isaacsim_vscode_filename}")
FileNotFoundError: Could not find the isaac-sim settings file: .vscode/settings.json`

I read this [thread ](https://forums.developer.nvidia.com/t/failed-to-install-isaac-lab/295578) about the same issue, but the recommendations are for installing using binaries.

Thank you in advance!

**Comment by Mayankm96** [comment] 2024-07-03 17:20
Closing as this a duplicate of #629, #620.

Please check the MR #628 to see if that solves the issue for you.

**Closed by Mayankm96** 2024-07-03 17:20 UTC
Labels: bug, duplicate
