### ISSUE TITLE
Docker: Could not open asset

### ISSUE THREAD

**Issue by swstbecrpgmail** [isaac-sim/IsaacLab#612] opened 2024-07-01 15:22 UTC
When I run "./orbit.sh -p source/standalone/demos/quadrupeds.py --livestream 1" , it reports that "Could not open asset".
![image](https://github.com/isaac-sim/IsaacLab/assets/153968462/474de3de-ccd2-4f42-b4c3-324152ee8b03)
 
I have never met this problem before, if anyone has potential solutions, feel free to leave comments.
Thank you very much!

**Comment by Mayankm96** [comment] 2024-07-02 04:36
Duplicate of #611

**Closed by Mayankm96** 2024-07-02 04:36 UTC
Labels: duplicate
