### ISSUE TITLE
[Question] Can I use different objects in different sub_environments, like Isaacgym?

### ISSUE THREAD

**Issue by yichaoshen-MS** [isaac-sim/IsaacLab#920] opened 2024-09-02 15:21 UTC
### Question

In IsaacGym, sub-environments are created using a for-loop, allowing each sub-environment to load different objects, thereby enabling diversity. However, in IsaacLab, sub-environments are cloned to create multiples of the same environment. I'm unsure how to introduce diversity among these cloned sub-environments. Any suggestions?

**Comment by zoctipus** [comment] 2024-09-02 22:50
I believe Mayank introduced a script that does this!
https://github.com/isaac-sim/IsaacLab/issues/186#issuecomment-1943465375

**Comment by Mayankm96** [comment] 2024-09-05 08:19
Closing this issue as this is a duplicate of #186. We have an MR underworks for this feature: #895

**Closed by Mayankm96** 2024-09-05 08:19 UTC
